### ISSUE TITLE
FEATURE: Remove dependency "watchman"

### ISSUE THREAD

**Issue by DanielHabenicht** [prisma-labs/vscode-graphql#116]
## Actual Behavior

Users who want to use this extension have to install watchman. This is more time-consuming than just clicking install in VSCode. (especially for Windows Users)

## Expected Behavior

The VSCode extension should be a one-click install.

## Steps to Reproduce the Problem Or Description

Install it on your system.

## Specifications

  - GraphQL for VSCode Extension Version: Preview [Unreleased]
  - VSCode Version: 1.35.1
  - OS Name: Windows
  - OS Version: 10

## Logs Of TS Server || GraphQL Language Service
should not be needed

**Comment by DanielHabenicht** [comment]
I don't know a thing about typescript extensions, but other node based tools are using [Chokidar](https://www.npmjs.com/package/chokidar)

**Comment by Bdthomson** [comment]
+1

**Comment by lostfictions** [comment]
For reference, here's the process a user has to go through to get this extension working:

Go to the Watchman website

![Screenshot from 2019-12-23 20-21-37](https://user-images.githubusercontent.com/567041/71387447-e8085f00-25c1-11ea-8c2c-0c467f2966f1.png)

![image](https://user-images.githubusercontent.com/567041/71387397-b98a8400-25c1-11ea-999a-a853b7faf5b1.png)

Hmm, looks like all the installs are beta. And my operating system isn't supported. Let's give it a shot anyway.

![Screenshot from 2019-12-23 20-23-01](https://user-images.githubusercontent.com/567041/71387486-1b4aee00-25c2-11ea-8d11-a9526107d2bf.png)

![image](https://user-images.githubusercontent.com/567041/71387491-243bbf80-25c2-11ea-8aa2-64f7a631d2ce.png)

Okay. Let's comb the Watchman issues, I guess?

![Screenshot from 2019-12-23 20-24-51](https://user-images.githubusercontent.com/567041/71387536-59e0a880-25c2-11ea-86a5-d8e0d60ed6c9.png)

Ah, I guess I have to be a logged-in Github user, or my journey as a potential user of this extension ends here. I also note with bemusement there's an issue called "Binaries seem broken on linux" which bodes well for me. But at least I know where to get the binaries!

![image](https://user-images.githubusercontent.com/567041/71387604-9dd3ad80-25c2-11ea-9764-f1479a4ce5f0.png)

I... guess I'll just download a random build off master that passed CI? Maybe?

![image](https://user-images.githubusercontent.com/567041/71387666-dffcef00-25c2-11ea-9b2e-1dd9f120b7b1.png)

So... okay. I need to put this 175mb binary on my PATH? Sounds legit.

![image](https://user-images.githubusercontent.com/567041/71387713-27837b00-25c3-11ea-82fb-9c052bffa379.png)

Gotta remember to mark the executable bit.

![image](https://user-images.githubusercontent.com/567041/71387752-60235480-25c3-11ea-8622-059124c525ff.png)

Well, I guess it doesn't work after all. That's that!

I'm genuinely curious how many users actually use this extension for anything more than syntax highlighting, since Watchman really doesn't seem to want people to use it!

**Comment by info-house-by** [comment]
doesn't work for me on Windows 10. I installed watchman for react-native projects. But it doesn't work here anyway.

Getting errors: 
Unable to open 'schema.graphql': Unable to read file '\\d:\\app\schema.graphql' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\d:\\app\schema.graphql').

**Comment by skurgansky-sugarcrm** [comment]
https://github.com/graphql/graphiql/tree/master/packages/graphql-language-service#dependencies
Watchman is dropped as dependency.

**Comment by acao** [comment]
yes good news! my latest minor version of the `graphql-language-service-server` has dropped watchman support. `graphql-language-service` is not used by this extension FYI

**Comment by acao** [comment]
would anyone want to test a pre-release for this, despite the regression? and let me know if you experience a performance boost?

**Comment by DanielHabenicht** [comment]
I think I would rather wait, as opening all .tsx files can be more time consuming than installing Watchman especially for big projects as it is also repeated work each time you open vscode. 
(it is a "time-consuming steps to install Watchman" Vs "opening definitions EVERY TIME")

But I am also not using this extension anymore, since I don't work with graphql anymore :/ - so it up to you.

**Comment by lostfictions** [comment]
@acao thanks so much for your work on this! for my part i'm not currently working on a gql-based project so wouldn't be able to provide feedback on a pre-release now, but it seems like a good idea! it'll definitely be appreciated as soon as i'm back working on codebases with gql :)

that said, re: your previous comment, i'm not sure about cutting a regular release with a functionality regression -- it seems like that would disrupt current users a fair bit, so it might be better to keep it as a pre-release until there's functionality parity?

**Comment by acao** [comment]
0.3.1 released! please open new tickets if you have any issues
