### ISSUE TITLE
Obtuse error when starting

### ISSUE THREAD

**Issue by ThisIsMissEm** [prisma-labs/vscode-graphql#23]
I just tried to set up the plugin for a project I'm working on where we have a monorepo — frontend & backend code in one repo. I've added a `.graphqlconfig` to the root of the project with:

```json
{
  "schemaPath": "backend/src/sys/graphql/schema.graphql",
  "includes": ["*.graphql"],
  "extensions": {
    "endpoints": {
      "dev": {
        "url": "http://localhost:22015/graphql",
        "headers": {
          // secret-removed
        }
      }
    }
  }
}
```

The error I receive is:

```Request initialize failed with message: Parsing <project path>/.graphqlconfig file has failed. Unexpected token } in JSON at position 277```

**Comment by divyenduz** [comment]
@ThisIsMissEm : Thanks for raising the issue. Unable to replicate it so far but the issue comes from [here](https://github.com/prismagraphql/graphql-config/blob/master/src/utils.ts#L29). Maybe the config was still an invalid JSON when then extension loaded? It looks like the error is from `JSON.parse`. 

Can you please confirm if it is still the case?

**Comment by Akryum** [comment]
I have found the extension to only work with `.graphqlconfig.yml`.

**Comment by jkelin** [comment]
The issue for me was that vscode autoformat has inserted a `,` after last `}`, which is valid with JSON5 but invalid in old JSON.

**Comment by divyenduz** [comment]
This is related https://github.com/prisma/graphql-config/issues/119

**Comment by acao** [comment]
i believe the new `graphql-config@3.0.0` also supports json5 config, if folks want comments in json :D

**Comment by acao** [comment]
0.3.1 released! please open new tickets if you have any issues
