### ISSUE TITLE
Hover not working

### ISSUE THREAD

**Issue by peterschussheim** [prisma-labs/vscode-graphql#29]
Currently when hovering over a variable the highlighting changes but there is no intellisense provided.

**Comment by marktani** [comment]
What is a token?

**Comment by peterschussheim** [comment]
Edited original post.  Token in this context refers to a variable or symbol in the editor.

**Comment by divyenduz** [comment]
@peterschussheim : Thanks for reporting this, can you please share a screenshot of the symbol on which hover does not work? 

Currently, we only support hover for `NamedType` and `Directive`. If this is for a variable then it is an `enhancement` and not a `bug`. Thanks.

**Comment by peterschussheim** [comment]
@divyenduz What is the roadmap for complete hover support?

**Comment by divyenduz** [comment]
@peterschussheim : Currently, we are awaiting feedback and estimating the amount of work for complete support as it will span across both language services (GraphQL and TS). Can you please share a screenshot of your specific case?

**Comment by peterschussheim** [comment]
here is a screenshot of hovers in kumar harsh's extension:

![](http://g.recordit.co/UjeezU0IBT.gif)

**Comment by divyenduz** [comment]
Thanks for sharing the image. Such a "peek definition" is already there. In this extension, you need to press cmd + hover to get a "peek".

![](http://g.recordit.co/nYJ4ob4UiE.gif)

We support this for type definition, input definition, enum definition, fragment definitions. 

Does this information solve it for you? Do you think we can document it better to enhance the experience. 

Please feel free to raise a PR to make it better or suggest here. Thanks!

**Comment by peterschussheim** [comment]
What about support for:

- `DateTime`
- `String`
- `Int`

**Comment by marktani** [comment]
> In this extension, you need to press cmd + hover to get a "peek".
I didn't know about this!! It's like a hidden gem 😄Not sure how we can better document this.

**Comment by divyenduz** [comment]
@peterschussheim : DateTime, String, Int have hover support for "test definition" already, not sure where they can go when peeked into because they don't have a physical type definition. 

@marktani : It is a side effect of creating "go to" definition. That is how VSCode works. 
The other extension chooses to show "peek" in hover in place of "comment", which is incorrect IMO as it won't show anything for built-in types or have separate code paths for it. Not sure.

**Comment by felixfbecker** [comment]
Most intellisense extensions show both the declaration line and the documentation (comment) of the field rendered as markdown with a hover provider

**Comment by acao** [comment]
I tried this actually - the issue here i found, is that if we print the type on hover as you suggest @felixfbecker, then when users ctrl/cmd-click to peek definition, it renders it unreadable/unusable, because the type is printed in duplicate and cut off

its more practical to have the full type documentation printed, and if you want to peek the type representation, then you can

moving to the appropriate repository
